version: '3'

services:
  app:
    image: app
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASS: password
      MYSQL_PORT: "3306"
    ports:
      - 9090:9090
    depends_on:
      - mysql
    command: sh -c "sleep 10 && app"

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306