apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-goapp
spec:
  type: NodePort
  selector:
    run: goapp
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30007
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-mysql
spec:
  selector:
    run: mysql
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306